<a href="https://colab.research.google.com/github/ErosVillegass/Programmation-101/blob/main/Clase05/03_estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios
**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

In [ ]:
user_input ={'nombre': "Eros" ,
 'edad': 31 ,
 'Apellido': 'Aranibar' ,
 'Hobbies' : "High Performance"
}

In [ ]:
user_input.keys()  #Retorna las keys del diccionario.

dict_keys(['nombre', 'edad', 'Apellido', 'Hobbies'])

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona) #Imprimiendo el diccionario

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))
print('Edad:', persona['edad'])

Nombre: Ana
Ciudad: Lima
Edad: 30


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
persona['EstatusSocial'] = 'Soltera'
persona['Educación'] = 'Bachier Culminado'


print(persona)



{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera', 'EstatusSocial': 'Soltera', 'Educación': 'Bachier Culminado'}


In [ ]:
# Eliminar un par clave-valor
persona.keys()
del persona['Educación']



print(persona)

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera', 'EstatusSocial': 'Soltera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['nombre', 'edad', 'profesion', 'EstatusSocial'])


In [ ]:
# Obtener todos los valores
print(persona.values())
print(user_input.values())

dict_values(['Ana', 30, 'Ingeniera', 'Soltera'])
dict_values(['Eros', 31, 'Aranibar', 'High Performance'])


In [ ]:
# Comprobar si una clave existe en el diccionario
print(persona.keys())
if 'profesion' in persona:
    print("La clave 'profesion' está en el diccionario.")
else:
    print("No existe educación")

dict_keys(['nombre', 'edad', 'profesion', 'EstatusSocial'])
La clave 'profesion' está en el diccionario.


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [ ]:
car_data = {'marca':'chino', 'modelo':'pirata', 'año':'1995','color':'caqui'}
print(car_data['marca'])
print(car_data['modelo'])
print(car_data['año'])
print(car_data['color'])
car_data['precio'] = 35
del car_data['color']
print(car_data)
print(car_data.keys())
print(car_data.values())

chino
pirata
1995
caqui
{'marca': 'chino', 'modelo': 'pirata', 'año': '1995', 'precio': 35}
dict_keys(['marca', 'modelo', 'año', 'precio'])
dict_values(['chino', 'pirata', '1995', 35])


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

Operaciones mas importantes a set


In [ ]:
lista1=['Columna1','columna2', 'columna3', ' columna4']
lista2=['Columna5','columna6', 'columna3', ' columna4']

lista1+lista2
list(set(lista1+lista2))

list(set(lista1)-set(lista2))

['Columna1', 'columna2']

In [ ]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


In [ ]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


### Ejemplo 2.2: Operaciones de Conjuntos


In [ ]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [ ]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 2, 3, 4, 5, 6, 7}


In [ ]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados. **texto en negrita**

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [1]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
matriz_one = [[1,2,3],
              [4,5,6],
              [7,8,9]]
print(matriz_one)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
print("Elemento en [0][0]", matriz[1][0])

Elemento en [0][0] 4


In [ ]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


In [ ]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


In [14]:
import numpy as np
my_array = np.array([[[1,2,3],
                     [4,5,6],
                     [8,9,10]],

                    [[1,2,3],
                     [4,5,6],
                     [8,9,10]
                    ]])

my_new_array = np.array([[[1,2,3],
                         [1,2,3],
                         [1,2,3]],

                         [[1,2,3],
                         [1,2,3],
                         [1,2,3],
                        ]])

print(my_new_array)
print(my_array)

my_array.shape # Forma de la matriz with numpy. Dimensiones (2,3,3) = 2 matrices de 3x3
my_new_array.shape


[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]]]


(2, 3, 3)

In [ ]:
print(my_array+10)

[[[11 12 13]
  [14 15 16]
  [18 19 20]]

 [[11 12 13]
  [14 15 16]
  [18 19 20]]]


In [ ]:
print(my_array*2)

[[[ 2  4  6]
  [ 8 10 12]
  [16 18 20]]

 [[ 2  4  6]
  [ 8 10 12]
  [16 18 20]]]


In [17]:
matrix_new = np.array([[1,2,2],
                       [2,2,2],
                       [3,3,3]])

print(matrix_new)
matrix_new.shape

[[1 2 2]
 [2 2 2]
 [3 3 3]]


(3, 3)

### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [ ]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



In [ ]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [18]:
import numpy as np
import random

matriz_four_dimension = np.array([[random.randint(1,100),random.randint(1,100),random.randint(1,100),random.randint(1,100)  ],
                         [random.randint(1,100),random.randint(1,100),random.randint(1,100), random.randint(1,100) ],
                         [random.randint(1,100),random.randint(1,100),random.randint(1,100), random.randint(1,100) ],
                         [random.randint(1,100),random.randint(1,100),random.randint(1,100), random.randint(1,100) ]
                         ])

print(matriz_four_dimension)



[[17 38 88 85]
 [54 42 14 98]
 [57  9 86  3]
 [97 92 52 59]]


In [19]:
import numpy as np
import random
lista = [random.randint(1,100) for x in range(0,4)]
lista_one = [random.randint(1,100) for x in range(0,4)]
lista_two = [random.randint(1,100) for x in range(0,4)]
lista_three = [random.randint(1,100) for x in range(0,4)]

matriz_four_dimension = np.array([lista,
                         lista_one,
                         lista_two,
                         lista_three
                         ])

print(matriz_four_dimension)

[[48 27 95 56]
 [66  5 29 49]
 [29 65 91  7]
 [46  5 89 14]]


In [20]:
np.random.rand(4,4)

array([[0.35844143, 0.92603542, 0.38454548, 0.55964874],
       [0.77526073, 0.1291875 , 0.34651964, 0.42336006],
       [0.93202408, 0.3961465 , 0.23210089, 0.31867666],
       [0.61198023, 0.58559371, 0.82349806, 0.04880886]])

In [21]:
np.random.rand(5,5)

array([[0.57350679, 0.71375196, 0.64555785, 0.15826364, 0.43785912],
       [0.5018584 , 0.00935681, 0.3436904 , 0.47186165, 0.8370495 ],
       [0.13488975, 0.9993017 , 0.05211603, 0.06930706, 0.51529576],
       [0.53101566, 0.43907921, 0.41228194, 0.4828039 , 0.59067944],
       [0.61922893, 0.96403989, 0.77366459, 0.04246783, 0.23644012]])

## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [33]:
sold_phones = [100, 200, 145,200,450, 100,100]
sold_laptops = [100, 200, 145,200,4550, 110,150]
sold_tables = [100, 200, 145,200,4500, 1200,160]

print(sold_phones[-3:])
print(sold_laptops[-3:])
print(sold_tables[-3:])

total_phone = sum(sold_phones)/len(sold_phones)
total_laptops = sum(sold_laptops)/len(sold_laptops)
total_tables = sum(sold_tables)/len(sold_tables)

print(total_phone,total_laptops,total_tables)
total_sold = [total_phone, total_laptops,total_tables]

for x in total_sold:
    if x > 5 :
      print("venta alta")
    else:
      print("venta baja")





[450, 100, 100]
[4550, 110, 150]
[4500, 1200, 160]
185.0 779.2857142857143 929.2857142857143
venta alta
venta alta
venta alta


---

# Gracias por completar este laboratorio!

---