<a href="https://colab.research.google.com/github/ErosVillegass/Programmation-101/blob/main/Clase05/03_estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios
**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

In [ ]:
user_input ={'nombre': "Eros" ,
 'edad': 31 ,
 'Apellido': 'Aranibar' ,
 'Hobbies' : "High Performance"
}

In [ ]:
user_input.keys()  #Retorna las keys del diccionario.

dict_keys(['nombre', 'edad', 'Apellido', 'Hobbies'])

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona) #Imprimiendo el diccionario

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))
print('Edad:', persona['edad'])

Nombre: Ana
Ciudad: Lima
Edad: 30


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
persona['EstatusSocial'] = 'Soltera'
persona['Educación'] = 'Bachier Culminado'


print(persona)



{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera', 'EstatusSocial': 'Soltera', 'Educación': 'Bachier Culminado'}


In [ ]:
# Eliminar un par clave-valor
persona.keys()
del persona['Educación']



print(persona)

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera', 'EstatusSocial': 'Soltera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['nombre', 'edad', 'profesion', 'EstatusSocial'])


In [ ]:
# Obtener todos los valores
print(persona.values())
print(user_input.values())

dict_values(['Ana', 30, 'Ingeniera', 'Soltera'])
dict_values(['Eros', 31, 'Aranibar', 'High Performance'])


In [ ]:
# Comprobar si una clave existe en el diccionario
print(persona.keys())
if 'profesion' in persona:
    print("La clave 'profesion' está en el diccionario.")
else:
    print("No existe educación")

dict_keys(['nombre', 'edad', 'profesion', 'EstatusSocial'])
La clave 'profesion' está en el diccionario.


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [ ]:
car_data = {'marca':'chino', 'modelo':'pirata', 'año':'1995','color':'caqui'}
print(car_data['marca'])
print(car_data['modelo'])
print(car_data['año'])
print(car_data['color'])
car_data['precio'] = 35
del car_data['color']
print(car_data)
print(car_data.keys())
print(car_data.values())

chino
pirata
1995
caqui
{'marca': 'chino', 'modelo': 'pirata', 'año': '1995', 'precio': 35}
dict_keys(['marca', 'modelo', 'año', 'precio'])
dict_values(['chino', 'pirata', '1995', 35])


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

Operaciones mas importantes a set


In [ ]:
lista1=['Columna1','columna2', 'columna3', ' columna4']
lista2=['Columna5','columna6', 'columna3', ' columna4']

lista1+lista2
list(set(lista1+lista2))

list(set(lista1)-set(lista2))

['Columna1', 'columna2']

In [4]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


In [ ]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


### Ejemplo 2.2: Operaciones de Conjuntos


In [6]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [5]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 2, 3, 4, 5, 6, 7}


In [7]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [8]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [9]:
matriz_one = [[1,2,3],
              [4,5,6],
              [7,8,9]]
print(matriz_one)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [12]:
print("Elemento en [0][0]", matriz[1][0])

Elemento en [0][0] 4


In [ ]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


In [13]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


In [21]:
import numpy as np
my_array = np.array([[[1,2,3],
                     [4,5,6],
                     [8,9,10]],

                    [[1,2,3],
                     [4,5,6],
                     [8,9,10]
                    ]])


print(my_array)
my_array.shape # Forma de la matriz with numpy. Dimensiones (2,3,3) = 2 matrices de 3x3



[[[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 8  9 10]]]


(2, 3, 3)

In [22]:
print(my_array+10)

[[[11 12 13]
  [14 15 16]
  [18 19 20]]

 [[11 12 13]
  [14 15 16]
  [18 19 20]]]


In [23]:
print(my_array*2)

[[[ 2  4  6]
  [ 8 10 12]
  [16 18 20]]

 [[ 2  4  6]
  [ 8 10 12]
  [16 18 20]]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [14]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



In [ ]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [32]:
import numpy as np
import random

matriz_four_dimension = np.array([[random.randint(1,100),random.randint(1,100),random.randint(1,100),random.randint(1,100)  ],
                         [random.randint(1,100),random.randint(1,100),random.randint(1,100), random.randint(1,100) ],
                         [random.randint(1,100),random.randint(1,100),random.randint(1,100), random.randint(1,100) ],
                         [random.randint(1,100),random.randint(1,100),random.randint(1,100), random.randint(1,100) ]
                         ])

print(matriz_four_dimension)



[[ 37  43  16  36]
 [ 58  74  60  38]
 [ 12  80  60  15]
 [100  48  55  80]]


In [72]:
import numpy as np
import random
lista = [random.randint(1,100) for x in range(0,4)]
lista_one = [random.randint(1,100) for x in range(0,4)]
lista_two = [random.randint(1,100) for x in range(0,4)]
lista_three = [random.randint(1,100) for x in range(0,4)]

matriz_four_dimension = np.array([lista,
                         lista_one,
                         lista_two,
                         lista_three
                         ])

print(matriz_four_dimension)

[[100  13  87  20]
 [ 46  82  86  12]
 [  9  23  94  39]
 [ 40  16  88  87]]


In [74]:
np.random.rand(4,4)

array([[0.03467346, 0.56631532, 0.90428777, 0.75163453],
       [0.15387352, 0.10545975, 0.19553751, 0.04096015],
       [0.72373455, 0.9660758 , 0.90927031, 0.91936943],
       [0.71584973, 0.56002655, 0.81930066, 0.52610792]])

In [75]:
np.random.rand?

## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

---

# Gracias por completar este laboratorio!

---